### ISSUE TITLE
Batch request issue

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-php#227]
https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Index.php#L1048

should be implemented like in the client

https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L625

We need to keep BC

We will then be able to remove the custom_batch snippet that is used only for php

**Comment by julienbourdeau** [comment]
I'm not sure I understood the issue but why not having something like:

```php
// src/AlgoliaSearch/Index.php

public function getApiKey($key)
{
    return $this->client->getApiKey($key);
}
```

**Comment by julienbourdeau** [comment]
I believe this was fixed, let me know if I misunderstood.

**Comment by maxiloc** [comment]
No this is not fixed
https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L989
https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Index.php#L1363

**Comment by maxiloc** [comment]
We should pass  array('requests' => $requests) in index as well

**Comment by julienbourdeau** [comment]
Fix in v2:

* batch methods takes operations not nested under `requests`: https://github.com/algolia/algoliasearch-client-php/blob/92b540c921a0f6b7b7de9eedfb2bfff8fce2dff1/src/Index.php#L238

* `Helpers::buildBatch` returns a batch not nested under `requests`: https://github.com/algolia/algoliasearch-client-php/blob/92b540c921a0f6b7b7de9eedfb2bfff8fce2dff1/src/Support/Helpers.php#L68-L75
